//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WumpusEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CaveFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CaveFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WumpusEngine.Cave.CaveFiles", typeof(CaveFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 26 2 5 1 2
        ///1 7 8 5 4 3
        ///26 27 9 5 0 3
        ///28 5 9 3 1 4
        ///4 6 30 4 2 1
        ///5 11 5 4
        ///2 8 12 1 2 4
        ///2 7 14 0 5 3
        ///3 4 10 0 1 2
        ///9 11 15 5 1 4 
        ///10 17 6 4 3 1
        ///17 13 7 4 2 1
        ///12 18 19 5 4 3
        ///19 8 21 4 0 2
        ///10 16 1 2
        ///15 21 22 5 4 3
        ///11 12 22 5 4 3
        ///23 24 13 4 3 1
        ///24 13 14 4 0 1
        ///25 27 4 2
        ///14 16 27 5 1 3
        ///16 29 28 0 2 3
        ///17 18 0 1
        ///18 19 25 0 1 2
        ///24 20 26 5 1 2
        ///25 1 3 5 4 2
        ///20 21 3 5 0 3
        ///22 29 4 0 1 3
        ///22 28 30 5 4 2
        ///29 5 1 5 4 2.
        /// </summary>
        internal static string Layout1 {
            get {
                return ResourceManager.GetString("Layout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 2 7 0 2 3
        ///1 8 3 5 3 1
        ///2 9 4 4 3 1
        ///3 5 11 5 1 2
        ///4 6 4 2
        ///5 12 4 2
        ///1 13 8 0 3 2
        ///7 2 9 5 0 1
        ///3 8 10 0 4 2
        ///9 15 16 5 4 3
        ///4 17 12 5 3 2
        ///6 11 18 0 5 3
        ///7 14 19 0 2 3
        ///13 20 15 5 3 1
        ///14 21 10 4 3 1
        ///10 22 17 0 3 1
        ///16 23 11 4 3 0
        ///12 23 0 4
        ///13 20 25 0 2 3 
        ///19 14 27 5 0 2
        ///15 22 0 2
        ///21 16 29 5 0 2 
        ///17 18 24 0 1 2 
        ///23 29 30 5 4 3
        ///19 26 0 2 
        ///25 26 5 2
        ///20 26 28 5 4 2
        ///27 29 5 1
        ///22 28 24 5 4 1
        ///1 24 3 0.
        /// </summary>
        internal static string Layout2 {
            get {
                return ResourceManager.GetString("Layout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25 6 7 0 4 3
        ///7 8 9 4 3 2
        ///26 9 4 5 3 2
        ///3 28 10 5 0 3
        ///29 6 11 0 2 3
        ///5 1 7 5 1 2 
        ///6 1 2 5 0 1 
        ///2 13 14 0 4 3
        ///2 3 15 5 0 3
        ///4 15 16 0 4 3
        ///5 12 17 0 2 3
        ///11 17 5 4
        ///18 19 8 4 3 1
        ///19 8 15 4 0 1
        ///14 9 10 4 0 1
        ///10 23 21 0 2 4
        ///11 12 18 0 1 2
        ///17 13 23 5 1 4
        ///24 13 14 4 0 1
        ///25 21 27 4 1 2
        ///20 16 27 4 1 3
        ///28 29 23 3 2 1
        ///16 22 18 5 4 1
        ///19 25 30 1 2 3
        ///24 1 20 5 3 1
        ///27 3 1 2
        ///26 20 21 4 5 0
        ///22 4 0 3
        ///22 5 30 5 3 2
        ///29 24 5 0.
        /// </summary>
        internal static string Layout3 {
            get {
                return ResourceManager.GetString("Layout3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 6 7 5 4 3
        ///7 8 9 4 3 2
        ///27 4 9 0 2 3
        ///3 28 11 5 0 2
        ///29 30 11 0 1 3
        ///1 12 1 3
        ///12 1 2 4 0 1
        ///2 13 0 4
        ///2 3 15 5 0 3
        ///11 17 16 1
        ///4 10 5 5 4 0
        ///6 7 0 1
        ///18 19 8 4 3 1
        ///19 15 21 4 1 2
        ///14 9 16 4 0 2
        ///15 10 17 5 0 1
        ///10 16 18 5 4 2
        ///17 23 13 5 4 1
        ///24 13 14 4 0 1
        ///25 26 21 4 3 1
        ///14 20 27 5 4 3
        ///27 28 23 4 3 1
        ///22 18 4 1
        ///29 19 4 1
        ///30 20 26 4 1 2
        ///25 20 5 0
        ///21 22 3 0 1 3
        ///22 29 4 0 1 3
        ///28 5 24 4 3 1
        ///5 1 25 4 2 1.
        /// </summary>
        internal static string Layout4 {
            get {
                return ResourceManager.GetString("Layout4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 26 2 4 1 2
        ///1 26 9 5 0 2
        ///26 9 4 5 3 2
        ///3 9 10 5 4 3
        ///29 30 6 0 1 2
        ///5 1 7 5 1 2
        ///6 12 8 5 4 2
        ///7 14 15 5 3 2
        ///2 3 4 5 0 1
        ///15 4 11 4 0 1
        ///10 17 12 4 3 2
        ///11 18 7 5 3 1
        ///12 19 14 5 3 2
        ///13 8 20 5 0 3
        ///8 10 21 5 1 3
        ///21 22 17 4 3 1
        ///16 11 18 4 0 2
        ///17 12 24 5 0 3
        ///13 20 25 0 2 3
        ///25 19 14 4 5 0
        ///15 16 27 0 1 3
        ///16 23 28 0 1 3
        ///22 29 24 4 3 2
        ///23 18 30 5 0 3
        ///30 19 20 4 0 1
        ///1 2 3 4 3 2
        ///21 28 0 2
        ///27 22 29 5 0 1
        ///23 28 5 0 4 3
        ///5 24 25 4 0 1.
        /// </summary>
        internal static string Layout5 {
            get {
                return ResourceManager.GetString("Layout5", resourceCulture);
            }
        }
    }
}
